# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: selenium_tutorial
on:
 workflow_dispatch:
 schedule:
   - cron: "*/30 * * * *"
permissions:
  contents: read
env: # Or as an environment variable
      BASE_URL: ${{ secrets.BASE_URL }}
      UNAME: ${{ secrets.UNAME }}
      PASSWD: ${{ secrets.PASSWD }}
      INVALID_PASSWD: ${{ secrets.INVALID_PASSWD }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - uses: actions/checkout@v3
      if: success() || failure()
    - run: | 
            mkdir -p reports
            pytest  --html=reports/reports.html
            chmod 777  /home/runner/work/selenium_python_tutorial/selenium_python_tutorial/reports/reports.html

    - name: Set output
      if: success() || failure()
      id: results
      run: echo "artifactPath=reports/reports.html" >> $GITHUB_OUTPUT

    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-report
        path: ${{ steps.results.outputs.artifactPath }}





